### ISSUE TITLE
isPrivateAssetsAllSet has no effect

### ISSUE THREAD

**Issue by p-26** [DigitecGalaxus/ProjectsRuler#12] opened 2020-07-08 15:11 UTC
Though [we have a check in place that checks that references to Deblazer without PrivateAssets=All are forbidden](https://dev.azure.com/digitecgalaxus/devinite/_git/devinite?path=%2FOldMonolith%2Fdevinite.TestsWithoutDb%2FArchitecture%2FPackageReferencesSmokeTests.cs&version=GBmaster&line=25&lineEnd=25&lineStartColumn=17&lineEndColumn=176&lineStyle=plain), [no reference to Deblazer has PrivateAssets=all set](https://dev.azure.com/digitecgalaxus/devinite/_git/devinite?path=%2FCategoryManagement%2FDg.CategoryManagement.TestsWithDb%2FDg.CategoryManagement.TestsWithDb.csproj&version=GBmaster&line=27&lineEnd=27&lineStartColumn=5&lineEndColumn=60&lineStyle=plain).

**Comment by boskicthebrain** [comment] 2020-09-02 14:35
This works as intended. The appropriate test was missing. If you want to enforce something, you have to forbid the opposite. 

```
        [Test]
        [SmokeTest(TestModule.Architecture)]
        public void SomePackageReferencesHaveToSetPrivateAssetsToAll()
        {
            AssertReferenceRules(
                // Check for PrivateAssets set to all
                new ReferenceRule("*", "SomePackage", RuleKind.Forbidden, description: "SomePackage has to have PrivateAssets=\"All\" set.", isPrivateAssetsAllSet: false)
            );
        }
```

I admit that this is not the most intuitive way of achieving this, but it is the only way and I like that fact. If you like, you can open a feature request issue, to add an enforcing rule kind. I am closing this one, because it is not a bug and it works as intended.

**Closed by boskicthebrain** 2020-09-02 14:35 UTC
